workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "GameCatalog.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "GameCatalog" # Isikan nama scheme project Anda.
    scripts:
      - name: Run build only (skip tests)
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2' \
          clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - dk.harryadi@gmail.com
          
  ios-project-test: # new workflow for testing
    name: iOS Test # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "GameCatalog.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "GameCatalogTests" # Test scheme name - adjust if different
    scripts:
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2' \
          test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    publishing:
      email:
        recipients:
          - dk.harryadi@gmail.com